apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-workloads-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/rmkprabhu/gitops-workloads-aks
      revision: main
      files:
      - path: "teams/*.yaml"
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      project: default
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.branch}}'
        path: '{{.path}}'
        {{- if .helmChart }}
        helm:
          chart: '{{.helmChart}}'
          {{- if .version }}
          version: '{{.version}}'
          {{- end }}
        {{- else }}
        directory: {}
        {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
