apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-workloads-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: team-workloads-generator  # References generator above
  template:
    metadata:
      name: '{{appName}}-{{index}}'
    spec:
      ignoreDifferences:
      - group: argoproj.io
        kind: ApplicationSet
        jsonPointers:
        - /spec/template/spec/source/helm/version
      source:
        repoURL: https://github.com/rmkprabhu/gitops-workloads-aks
        targetRevision: main
        path: apps
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated: {}