apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-workloads
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/rmkprabhu/gitops-workloads-aks
      revision: main
      files:
      - path: "teams/*.yaml"
  template:
    metadata:
      name: '{{ .path.basenameNormalized }}'
      labels:
        team: '{{ .team }}'
    spec:
      project: default
      source:
        repoURL: '{{ .repoURL }}'
        targetRevision: '{{ .targetRevision }}'
        path: '{{ .path }}'
        {{- if .helmChart }}
        helm:
          releaseName: '{{ .helmChart }}'
          {{- if .valuesFile }}
          valueFiles:
          - '{{ .valuesFile }}'
          {{- end }}
          {{- if .helmValues }}
          values: |
{{ .helmValues | indent 12 }}
          {{- end }}
        {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
