apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-workloads-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/rmkprabhu/gitops-workloads-aks
      revision: main
      files:
      - path: "teams/*.yaml"
  template:
    metadata:
      name: '{{.path.basenameNormalized}}-app'
    spec:
      project: default
      source:
        repoURL: '{{ index . "repoURL" }}'
        targetRevision: '{{ index . "branch" }}'
        path: '{{ index . "path" }}'
        {{- if index . "helmChart" }}
        helm:
          chart: '{{ index . "helmChart" }}'
          {{- if index . "version" }}
          version: '{{ index . "version" }}'
          {{- end }}
        {{- else }}
        directory: {}
        {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index . "namespace" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
